Introducing a skeleton structure for the iOS library
firebase/firebase-continue pull request #16
Opened 2017-08-03 18:08 UTC by davidair

2017-08-03 18:13 UTC, AndreasRicci approved these changes

2017-08-04 14:27 UTC, paulb777 requested changes

2017-08-04 14:27 UTC, paulb777 commented on ios/FirebaseContinue/Example/FirebaseContinue/main.m
> +//
Copyright

2017-08-04 14:27 UTC, paulb777 commented on ios/FirebaseContinue/Example/Podfile.lock
> +PODS:
Podfile.lock should be in .gitignore and not checked. (They may be checked in for apps, but should not be for libraries)

2017-08-04 14:27 UTC, paulb777 commented on ios/FirebaseContinue/Example/Tests/Tests.m
> +//
copyright

2017-08-04 14:27 UTC, paulb777 commented on ios/FirebaseContinue/Example/Tests/Tests-Prefix.pch
> +//  The contents of this file are implicitly included at the beginning of every test case source file.
Delete or add copyright

2017-08-04 14:27 UTC, paulb777 commented on ios/FirebaseContinue/FirebaseContinue.podspec
> +  s.author           = { 'Andreas Ricci' => 'ricciandreas@gmail.com' }
Should be  s.authors          = 'Google, Inc.'

2017-08-04 14:27 UTC, paulb777 commented on ios/FirebaseContinue/Example/FirebaseContinue/FirebaseContinue-Prefix.pch
> +//
Delete or add copyright

2017-08-04 14:27 UTC, paulb777 commented on ios/FirebaseContinue/Example/FirebaseContinue.xcworkspace/contents.xcworkspacedata
> +<?xml version="1.0" encoding="UTF-8"?>
*.xcworkspace should be in .gitignore

2017-08-04 14:35 UTC, davidair commented on ios/FirebaseContinue/Example/FirebaseContinue/main.m
> +//
done

2017-08-04 14:35 UTC, davidair commented on ios/FirebaseContinue/Example/Tests/Tests.m
> +//
done

2017-08-04 14:36 UTC, davidair commented on ios/FirebaseContinue/Example/FirebaseContinue/FirebaseContinue-Prefix.pch
> +//
done

2017-08-04 14:37 UTC, davidair commented on ios/FirebaseContinue/Example/Podfile.lock
> +PODS:
done

2017-08-04 14:37 UTC, davidair commented on ios/FirebaseContinue/Example/Tests/Tests-Prefix.pch
> +//  The contents of this file are implicitly included at the beginning of every test case source file.
done

2017-08-04 14:37 UTC, davidair commented on ios/FirebaseContinue/FirebaseContinue.podspec
> +  s.author           = { 'Andreas Ricci' => 'ricciandreas@gmail.com' }
done

2017-08-04 15:15 UTC, paulb777 requested changes
And git rm the files now in the .gitignore

2017-08-04 15:42 UTC, paulb777 approved these changes

2017-08-04 15:43 UTC, merged